### ISSUE TITLE
Add support for default Events that trigger on custom values

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/sprout#204]
- When an entry is saved with specific lightswitch value? (supports any lightswitch fields found)
- When an entry is saved with specific text value? (supports plain text, dropdowns, anything with a text submission)

**Comment by johnwbaxter** [comment]
I would love to see this!!!

**Comment by BenParizek** [comment]
See the Notification Event Condition Builder in Craft 4 along with the Twig Expression Condition Rule or Craft Condition Rule API for further customization.
