### ISSUE TITLE
Error showing when adding new redirects

### ISSUE THREAD

**Issue by danfathom** [barrelstrength/sprout#257]
### Description

I've downloaded the Lite version on 2 different sites, and on both of them I get an error when adding a new redirect. The screenshot below shows the error.

![Screenshot 2023-07-19 at 12 57 49](https://github.com/barrelstrength/sprout/assets/92588022/8dc7d9f9-3137-49a3-9037-b2ba8270ec6c)

### How to reproduce

1. Download Sprout redirects Lite
2. Add new redirect
3. 3. Fill in 'Old URL', 'New URL' fields, and select 301 status code and set redirect to be 'enabled'
4. Click save and the error shows

### Sprout Version

4.45.1

### Craft Version

4.4.16

### Database Type Version

MySQL 5.7.32

**Comment by BenParizek** [comment]
I've just released v4.45.2 that fixes this. Thanks for reporting.

**Comment by danfathom** [comment]
Thanks for that, I understand it now requires Sprout 4.0.8? I've added this to my composer file but getting some errors. I don't suppose you could advise where i'm going wrong? Thanks


![Screenshot 2023-07-20 at 10 11 14](https://github.com/barrelstrength/sprout/assets/92588022/896959dc-444a-46c7-9b98-5f777403d082)

**Comment by BenParizek** [comment]
@danfathom I overlooked pushing the tag in the release. I've pushed up the tag and the upgrade should work now without you needing to add that package to your composer.json file. 

Sprout Redirects requires the `barrelstrength/sprout:4.0.8` so you shouldn't need to worry about it beyond just upgrading the plugin itself.

**Comment by danfathom** [comment]
Thanks for sorting that. I can confirm it's working as expected.
