### ISSUE TITLE
URL parameters not passing to new URL

### ISSUE THREAD

**Issue by Dean-Wilson** [barrelstrength/sprout#270]
### Description

Redirects aren't sending through any of the url parameters

### How to reproduce

For Example:

Old URL: events(\/*\?.*)?
New URL: network-and-events/events$1

Status Code 301
Match Strategy: Regular Expression

Test: /events?test=test
Expected: /network-and-events/events?test=test
Actual Result: /network-and-events/events

### Sprout Version

4.44.445

### Craft Version

4.4.8

### Database Type Version

5.7.mysql_aurora.2.11.2

**Comment by BenParizek** [comment]
There are scenarios when this is desirable and also scenarios where this is undesirable. There are also two global Redirects settings to help manage what result you want here. Have you explored the **Match Strategy** and **Query String Strategy** settings?

For your first example:

```
Old URL: events(/?.)?
New URL: network-and-events/events$1
```

You might consider the global settings:

```
Match Definition: URL (without query strings)
Query String Strategy: Append Query Strings
```

For your second example where you are trying to use the query string in the matched redirect:

```
Test: /events?test=test
Expected: /network-and-events/events?test=test
```

You might want those global settings to be:

```
Global Match Definition: URL (with query strings)
Global Query String Strategy: Append Query Strings
```
