### ISSUE TITLE
User permissions dont seem to work

### ISSUE THREAD

**Issue by bob-pixeldeluxe** [barrelstrength/sprout#271]
### Description

So we have a user group for our customers and we checked the following options
![Screenshot 2023-09-12 at 13 27 40](https://github.com/barrelstrength/sprout/assets/50947605/440f7042-8d4b-4b4b-8c98-3894c9f25571)
However when we log in as the customer we are able to access the data studio but none of the reports.

Now this is on an development enviroment withouth a license at the moment could it be related to that?

### How to reproduce

Create some reports.
Log in with a non admin user and see if you have access.

### Sprout Version

4.46.0

### Craft Version

4.5.3

### Database Type Version

mysql

**Comment by BenParizek** [comment]
@bob-pixeldeluxe I've just released Data Studio v4.46.1 that should fix these permission issues. 

fyi, all Craft and plugin features should work fine in a dev environment, regardless of license status. Thanks for reporting.
