### ISSUE TITLE
Dependency conflict with Composer

### ISSUE THREAD

**Issue by pverwoerd** [barrelstrength/sprout#273]
### Description

Thanks for releasing the v4 version with Craft 4 support 👏

We are getting a dependency problem in Composer when updating to v 4.44. The `barrelstrength/sprout-sitemaps` package has a requirement for `barrelstrength/sprout:^4.1.3.2` which is a non existing version. This results in a Composer conflict. See screenshot below.

![screenshot_from_2023-09-26_17-59-49](https://github.com/barrelstrength/sprout/assets/38130757/a58e7692-1573-48b3-9596-a825d3a67bdb)

### How to reproduce

composer require barrelstrength/sprout-sitemaps

### Sprout Version

4.44.444

### Craft Version

 4.5.5

### Database Type Version

Postgres

**Comment by BenParizek** [comment]
Sorry about that. I've pushed an update and it should be properly tagged now.
