### ISSUE TITLE
Uninstalling and re-installing throws an error

### ISSUE THREAD

**Issue by tr-lg** [barrelstrength/sprout#297]
### Description

It appears that not all data is properly deleted during uninstall. Here's the error I got:

```
Migration Error: An error occurred while executing the "BarrelStrength\Sprout\sentemail\migrations\m211101_000004_update_user_permissions migration: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sprout-module-sent-email:resendemails' for key 'idx_vcfllqibhtduuhlmpkijklgbebxmfwneyyli'
The SQL being executed was: INSERT INTO userpermissions (name, dateCreated, dateUpdated, uid) VALUES ('sprout-module-sent-email:resendemails', '2023-12-22 12:48:28', '2023-12-22 12:48:28', 'f4d3cd7d-a1b2-409c-9301-ae2ef51371ea')
```

### How to reproduce

1. Install "Sprout Email" plugin (lite)
2. Uninstall "Sprout Email" plugin
3. Install "Sprout Email" plugin (Lite)

### Sprout Version

4.44.444-beta.4

### Craft Version

Craft CMS PRO 4.5.13

### Database Type Version

mariadb:10.4

**Comment by BenParizek** [comment]
This issue has been resolved in Sprout Email v4.44.444-beta.5
