### ISSUE TITLE
Missing table "sprout_datasets"

### ISSUE THREAD

**Issue by tr-lg** [barrelstrength/sprout#298]
### Description

I installed the Sprout Email (lite) plugin and have errors in multiple locations because the "sprout_datasets" table doesn't exist.

Trying to create a data set results in a cryptic "Unable to save data set as a draft:" error. I used Xdebug to find that the original exception is "The table does not exist: {{%sprout_datasets}}".

When creating a new Audience, trying to select a data set doesn't show anything, but the async request returns this error: "Attempt to read property \"columns\" on null", which I tracked down to this line: https://github.com/barrelstrength/sprout/blob/v4/src/datastudio/components/elements/DataSetElementQuery.php#L36

### How to reproduce

1. Create a new Craft CMS installation using DDEV: https://ddev.readthedocs.io/en/latest/users/quickstart/#craft-cms
2. Install the Sprout Email plugin (Lite version): https://plugins.craftcms.com/sprout-email
3. In the main menu, click on Data Studio
4. Check the DevTools Console and note that the request to `index.php?p=admin%2Factions%2Felement-indexes%2Fget-elements` fails

### Sprout Version

4.44.444-beta.4

### Craft Version

Craft CMS PRO 4.5.13

### Database Type Version

mariadb:10.4

**Comment by BenParizek** [comment]
This issue is resolved in v4.44.444-beta.6
