### ISSUE TITLE
Return value type error on new DataSet element

### ISSUE THREAD

**Issue by elivz** [barrelstrength/sprout#308]
### Description

Calling `(string)$dataset` on a newly-created DataSet element (in my case, via the [Link Field](https://github.com/sebastian-lenz/craft-linkfield) plugin, which has an `Element::EVENT_AFTER_SAVE` event that runs that code) will fail with a "Return value must be of type string, null returned" error. This is because the default value of `DataSetElement::$name` is `null`, but the `__toString()` method has a return type of `string`. It looks like the simplest fix for this would be to just set the initial value as `$name = ''`.

### How to reproduce

1. Install Data Studio and the Link Field plugin
2. Try to create a new report in Data Studio

### Sprout Version

4.46.3

### Craft Version

4.4.15

### Database Type Version

MySQL

**Comment by BenParizek** [comment]
@elivz I've just released v4.46.4 which should resolve this and fallback to a string instead of null now.

**Comment by elivz** [comment]
Thanks, looking good now!
