### ISSUE TITLE
Cannot export dataset within multisite setup

### ISSUE THREAD

**Issue by superextinct** [barrelstrength/sprout#310]
### Description

When exporting a dataset which was created within a different site, an ElementNotFoundException is thrown.

### How to reproduce

1. Create a new report (regardless of type)
2. Export newly created report

### Sprout Version

4.46.3

### Craft Version

4.7.3

### Database Type Version

MySQL 8.0.33

**Comment by BenParizek** [comment]
Thanks @superextinct. Just pushed this fix live in v4.46.4
