### ISSUE TITLE
Crash on data set save

### ISSUE THREAD

**Issue by EricMgns** [barrelstrength/sprout#320]
### Description

When trying to save a Dataset with Date Range to anything but "Custom Date Range" Craft throws: 
>Cannot assign bool to property BarrelStrength\Sprout\datastudio\components\datasources\CommerceProductRevenueDataSource::$startDate of type ?DateTimeInterface

### How to reproduce

Create a new Dataset of type "Commerce Order History" or "Commerce Product Revenue", set Date Range to anything but "Custom Date Range" and attempt to save.

### Sprout Version

4.46.4

### Craft Version

4.8.8

### Database Type Version

MariaDB: 10.4

**Comment by BenParizek** [comment]
This has been fixed in Sprout Reports v4.46.6
