### ISSUE TITLE
Array in testToEmailAddress config throws error in control panel

### ISSUE THREAD

**Issue by medoingthings** [barrelstrength/sprout#324]
### Description

Having the `testToEmailAddress` setting set to an array instead of a string, the control panel for a set-up transactional email throws an error.

### How to reproduce

general.php:
```php
'testToEmailAddress' => array('email@example.com', 'email2@example.com'),
```

The result is an `Array to string conversion` error when trying to access the cp settings of an email (`/sprout/email/transactional-email/edit/[id]`)

### Sprout Version

4.44.444-beta.10

### Craft Version

4.9.5

### Database Type Version

MySQL

**Comment by BenParizek** [comment]
This has been addressed in v4.44.444-beta.12

Thanks for reporting.
