### ISSUE TITLE
Allow environment variables for configuration

### ISSUE THREAD

**Issue by marionnewlevant** [barrelstrength/sprout#88]
### The problem (description, use case, screenshots...)
It would be nice if the From Name, From Email, Reply To could vary based on the environment. Environment variables would be a convenient way to do this. admin/settings/email does this for System Email Address etc.

**Comment by BenParizek** [comment]
Related: https://github.com/barrelstrength/sprout/issues/94

**Comment by BenParizek** [comment]
This is now supported in Craft 4.
